attention_logit_softcapping: null
attention_scores_scalar: null
attn_bias: false
bias: false
block_size: 262144
final_logit_softcapping: null
first_k_dense_replace: null
gelu_approximate: none
head_size: 128
hf_config:
  name: Qwen3-4B-Instruct-2507
  org: Qwen
intermediate_size: 9728
latent_attention: null
lm_head_bias: false
mlp_class_name: LLaMAMLP
moe_intermediate_size: null
n_embd: 2560
n_expert: 0
n_expert_groups: null
n_expert_per_token: 0
n_head: 32
n_layer: 36
n_query_groups: 8
n_shared_expert: null
n_topk_groups: null
n_topk_scores_per_group: null
name: Qwen3-4B-Instruct-2507
norm_1: true
norm_2: true
norm_class_name: RMSNorm
norm_eps: 1.0e-06
norm_qk: true
norm_qk_type: default
norm_topk_prob: false
padded_vocab_size: 151936
padding_multiple: 512
parallel_residual: false
post_attention_norm: false
post_mlp_norm: false
rope_adjustments: null
rope_base: 5000000
rope_condense_ratio: 1
rope_indices: null
rope_local_base_freq: null
rotary_percentage: 1.0
routed_scaling_factor: 1.0
scale_embeddings: false
shared_attention_norm: false
sliding_window_indices: null
sliding_window_size: null
vocab_size: 151643
